package visao;


public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuItemEmprestimos = new javax.swing.JMenu();
        jMenuItemCadastrarFerramenta = new javax.swing.JMenuItem();
        jMenuItemCadastrarAmigo = new javax.swing.JMenuItem();
        jMenuItemGerenciarFerramentas = new javax.swing.JMenuItem();
        jMenuItemGerenciarAmigos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemDescricao = new javax.swing.JMenuItem();
        jMenuItemLicenca = new javax.swing.JMenuItem();
        jMenuItemCreditos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Strider empréstimos");

        jMenuItemEmprestimos.setText("Arquivo");
        jMenuItemEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmprestimosActionPerformed(evt);
            }
        });

        jMenuItemCadastrarFerramenta.setText("Cadastrar Ferramenta");
        jMenuItemCadastrarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarFerramentaActionPerformed(evt);
            }
        });
        jMenuItemEmprestimos.add(jMenuItemCadastrarFerramenta);

        jMenuItemCadastrarAmigo.setText("Cadastrar Amigo(a)");
        jMenuItemCadastrarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarAmigoActionPerformed(evt);
            }
        });
        jMenuItemEmprestimos.add(jMenuItemCadastrarAmigo);

        jMenuItemGerenciarFerramentas.setText("Gerenciar Ferramentas");
        jMenuItemGerenciarFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarFerramentasActionPerformed(evt);
            }
        });
        jMenuItemEmprestimos.add(jMenuItemGerenciarFerramentas);

        jMenuItemGerenciarAmigos.setText("Gerenciar Amigos");
        jMenuItemGerenciarAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarAmigosActionPerformed(evt);
            }
        });
        jMenuItemEmprestimos.add(jMenuItemGerenciarAmigos);

        jMenuItem1.setText("Emprestimos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuItemEmprestimos.add(jMenuItem1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuItemEmprestimos.add(jMenuItemSair);

        jMenuBar1.add(jMenuItemEmprestimos);

        jMenu3.setText("Sobre");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItemDescricao.setText("Decrição");
        jMenuItemDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDescricaoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemDescricao);

        jMenuItemLicenca.setText("Lincença");
        jMenuItemLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLicencaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemLicenca);

        jMenuItemCreditos.setText("Créditos");
        jMenuItemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreditosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCreditos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGerenciarFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarFerramentasActionPerformed
        FrmGerenciarFerramenta objeto = new FrmGerenciarFerramenta();
        objeto.setLocation(50, 200);
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemGerenciarFerramentasActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDescricaoActionPerformed
        Descricao descricao = new Descricao();
        descricao.setVisible(true);
    }//GEN-LAST:event_jMenuItemDescricaoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLicencaActionPerformed
        Licenca licenca = new Licenca();
        licenca.criarLicenca();
    }//GEN-LAST:event_jMenuItemLicencaActionPerformed

    private void jMenuItemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreditosActionPerformed
        Credito creditos = new Credito();
        creditos.criarCreditos();
    }//GEN-LAST:event_jMenuItemCreditosActionPerformed

    private void jMenuItemCadastrarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarFerramentaActionPerformed
        FrmCadastroFerramenta objeto = new FrmCadastroFerramenta();
        objeto.setLocation(50, 200);
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarFerramentaActionPerformed

    private void jMenuItemCadastrarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarAmigoActionPerformed
        FrmCadastroAmigo objeto = new FrmCadastroAmigo();
        objeto.setLocation(200, 200);
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarAmigoActionPerformed

    private void jMenuItemGerenciarAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarAmigosActionPerformed
        FrmGerenciarAmigo objeto = new FrmGerenciarAmigo();
        objeto.setLocation(200, 200);
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemGerenciarAmigosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmEmprestimo objeto = new FrmEmprestimo();
        objeto.setLocation(200, 200);
        objeto.setVisible(true);    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmprestimosActionPerformed
        FrmEmprestimo objeto = new FrmEmprestimo();
        objeto.setLocation(200, 200);
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuItemEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCadastrarAmigo;
    private javax.swing.JMenuItem jMenuItemCadastrarFerramenta;
    private javax.swing.JMenuItem jMenuItemCreditos;
    private javax.swing.JMenuItem jMenuItemDescricao;
    private javax.swing.JMenu jMenuItemEmprestimos;
    private javax.swing.JMenuItem jMenuItemGerenciarAmigos;
    private javax.swing.JMenuItem jMenuItemGerenciarFerramentas;
    private javax.swing.JMenuItem jMenuItemLicenca;
    private javax.swing.JMenuItem jMenuItemSair;
    // End of variables declaration//GEN-END:variables
}
